[feat] Add InfoWindow and Modal Appearance on Markers
calblueprint/ace-ny pull request #30
Opened 2024-10-21 11:49 UTC by ethan-tam33

## What's new in this PR
### Description
[//]: # "[Required] Describe what's new in this PR in a few lines. A description and bullet points for specifics will suffice."

- Needed to switch to @vis.gl/react-google-maps instead of @react-google-maps-api to use AdvancedMarker, which allows for InfoWindow
- Created a Map ID which is needed for  @vis.gl/react-google-maps
- InfoWindow renders upon hovering over AdvancedMarker
- ProjectModal renders upon clicking AdvancedMarker

### Screenshots
[//]: # "Add any screenshots that will help your PR reviewer understand what’s going on in the PR!"
[//]: # "[Required] For frontend tasks: add screenshots of the layout and expected behavior (GIFs if you’re feeling extra fancy)!"
[//]: # "Use the provided image template. Drag the desired image into the PR, then copy the link into the placeholder."

<img width="1215" alt="Screenshot 2024-10-21 at 4 44 16 AM" src="https://github.com/user-attachments/assets/2b2d9f65-c00b-4f23-9e05-4a0c15922027">

<img width="1215" alt="Screenshot 2024-10-21 at 4 44 41 AM" src="https://github.com/user-attachments/assets/093b178c-916a-4633-81e6-6c2a376608dd">

## How to review
[//]: # "/[Required] Describe the order in which to review files and what to expect when testing locally. Is there anything specifically you want feedback on? Should this be reviewed commit by commit, or all at once? What are some user flows to test? What are some edge cases to look out for?"

- api/maps/AddMarkers.tsx
- api/maps/MarkerInfoWindow.tsx
- components/Map/map.tsx

## Next steps
[//]: # "[Optional] - What has not yet been added to the PR, doesn’t yet have any functionality — essentially, what needs to be fixed or added."
[//]: # "[Optional] any temporary fixes in this PR that should be cleaned up later."

## Relevant links
### Online sources
https://visgl.github.io/react-google-maps/

### Related PRs
[//]: # "Add related PRs you're waiting on/ PRs that will conflict, etc; if this is a refactor, feel free to add PRs that previously modified this code"

CC: @itsliterallymonique

2024-10-22 07:36 UTC, itsliterallymonique requested changes
Could you make it so that the infowindows are not cut off if the marker is at the edge of the map? Can you also remove the x button since we are not using that.

2024-10-24 05:17 UTC, ethan-tam33 commented
@itsliterallymonique I just enabled auto pan for the map. Is this what you mean?

2024-10-25 01:29 UTC, jjstnlee approved these changes
Looks good to me! How come you removed the close button from the project modal though.

2024-10-25 21:33 UTC, itsliterallymonique approved these changes

2024-10-26 06:31 UTC, merged