32 - [feat] Continue Connecting NYISO and NYSERDA, and add Key Development Milestones
calblueprint/ace-ny pull request #39
Opened 2024-10-26 08:00 UTC by deenasun

## What's new in this PR
### Description
[//]: # "[Required] Describe what's new in this PR in a few lines. A description and bullet points for specifics will suffice."

### Screenshots
[//]: # "Add any screenshots that will help your PR reviewer understand what’s going on in the PR!"
[//]: # "[Required] For frontend tasks: add screenshots of the layout and expected behavior (GIFs if you’re feeling extra fancy)!"
[//]: # "Use the provided image template. Drag the desired image into the PR, then copy the link into the placeholder."

[image placeholder]: <img src="place image link here!!!" width="240" height="540">

## How to review
[//]: # "/[Required] Describe the order in which to review files and what to expect when testing locally. Is there anything specifically you want feedback on? Should this be reviewed commit by commit, or all at once? What are some user flows to test? What are some edge cases to look out for?"

## Next steps
[//]: # "[Optional] - What has not yet been added to the PR, doesn’t yet have any functionality — essentially, what needs to be fixed or added."
[//]: # "[Optional] any temporary fixes in this PR that should be cleaned up later."

## Relevant links
### Online sources
[//]: # "[Optional] insert links to any useful tutorials or documentation that you used for this PR!"

### Related PRs
[//]: # "Add related PRs you're waiting on/ PRs that will conflict, etc; if this is a refactor, feel free to add PRs that previously modified this code"

CC: @itsliterallymonique

2024-10-27 01:24 UTC, itsliterallymonique requested changes
Looking good Deena. Just make the 2 changes I commented on! thanks

2024-10-27 01:24 UTC, itsliterallymonique commented on api/webscraper/database_constants.py
> +  'H': 'Hydroelectric',
Add 'W': 'Land-Based Wind'

2024-10-27 01:24 UTC, itsliterallymonique commented on api/webscraper/nyserda_scraper.py
> +                    "proposed_cod": item.get("year_of_delivery_start_date", None),
don't get proposed COD from year_of_delivery_start_date. Only NYISO has the proposed COD

2024-10-28 04:16 UTC, deenasun commented on api/webscraper/nyserda_scraper.py
> +                    "proposed_cod": item.get("year_of_delivery_start_date", None),
@itsliterallymonique would you like me to remove the inclusion of the `proposed_cod` date from the NYSERDA small-scale solar projects as well? currently, we're using the "interconnection_date" field for the small-scale solar projects as an estimate for the proposed COD

2024-10-28 04:23 UTC, itsliterallymonique commented on api/webscraper/nyserda_scraper.py
> +                    "proposed_cod": item.get("year_of_delivery_start_date", None),
@deenasun hmmm. Let's keep that for now in the small-scale solar database. I will check with our POC if we can use interconnection_date for proposed_cod. I am not too sure if they are the same.

2024-10-28 04:37 UTC, deenasun commented on api/webscraper/nyserda_scraper.py
> +                    "proposed_cod": item.get("year_of_delivery_start_date", None),
Done!

2024-10-28 06:12 UTC, merged